# Generated by Django 4.0.2 on 2022-03-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('umail', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'newreg',
            },
        ),
    ]
