# Generated by Django 4.0.2 on 2022-03-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('accno', models.CharField(max_length=100)),
                ('bankname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'paydet',
            },
        ),
    ]
