# Generated by Django 3.2.12 on 2022-04-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_invitecodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecodes',
            name='eventid',
            field=models.CharField(max_length=200),
        ),
    ]
