# Generated by Django 3.2.12 on 2022-04-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_invitecodes_eventid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecodes',
            name='eventid',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='invitecodes',
            name='hashcode',
            field=models.CharField(max_length=200),
        ),
    ]
