# Generated by Django 3.2.12 on 2022-05-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20220430_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventid', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('attendence', models.CharField(max_length=20, null=True)),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'unique_together': {('eventid', 'username')},
            },
        ),
    ]
