# Generated by Django 3.2.12 on 2022-05-05 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_attendees_datetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userevents',
        ),
    ]
