# Generated by Django 3.2.12 on 2022-05-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_delete_userevents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendees',
            name='datetime',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
