# Generated by Django 4.0.2 on 2022-03-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.CharField(choices=[('silver', 'SILVER'), ('gold', 'GOLD'), ('platinum', 'PLATINUM')], default='silver', max_length=12)),
                ('price', models.FloatField()),
            ],
        ),
    ]
